apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-etc-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64mi
  storageClassName: local-gitlab-etc
kind: PersistentVolumeClaim
metadata:
  name: gitlab-log-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-gitlab-log
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-gitlab-data
