apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-etc-configmap
  namespace: default
data:
  gitlab.rb: |-
    # Docker options
    ## Prevent Postgres from trying to allocate 25% of total memory
    postgresql['shared_buffers'] = '256MB'
    postgresql['shmmax'] =  17179869184
    postgresql['shmall'] =  4194304
    
    # Manage accounts with docker
    #manage_accounts['enable'] = true
    
    # Get hostname from shell
    #host = `hostname`.strip
    #external_url "http://#{host}"
    
    # Load custom config from environment variable: GITLAB_OMNIBUS_CONFIG
    #eval ENV["GITLAB_OMNIBUS_CONFIG"].to_s
