apiVersion: v1
kind: Pod
metadata:
  name: gitlab-ce
  labels:
    name: gitlab-ce
spec:
  imagePullSecrets:
  - name: gitlab-registry
  containers:
  - name: gitlab-ce
    image: slpcat/gitlab-ce
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
      limits:
        memory: "4Gi"
        cpu: "2000m"       
    imagePullPolicy: Always
    ports:
    - name: ssh
      containerPort: 22
    - name: web
      containerPort: 80
    - name: ldap
      containerPort: 636
    - name: registry
      containerPort: 5000
    volumeMounts:
      - name: gitlab-etc 
        mountPath: "/etc/gitlab"
      - name: gitlab-log
        mountPath: "/var/log/gitlab"
      - name: gitlab-data
        mountPath: "/var/opt/gitlab"
  volumes:
    - name: gitlab-etc
      persistentVolumeClaim:
        claimName: gitlab-etc-claim
    - name: gitlab-log
      persistentVolumeClaim:
        claimName: gitlab-log-claim
    - name: gitlab-data
      persistentVolumeClaim:
        claimName: gitlab-data-claim
