apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-gitlab-data
