apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab
  #annotations:
  #  kubernetes.io/ingress.class: traefik
  #  ingress.kubernetes.io/auth-type: "basic"
  #  ingress.kubernetes.io/auth-secret: "mysecret"
spec:
  rules:
  - host: git.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: gitlab
          servicePort: 80
