apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-log-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-gitlab-log
