apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-etc-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64m
  storageClassName: local-gitlab-etc
