apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbd-provisioner
  namespace: ceph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbd-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rbd-provisioner
      #annotations:
        #net.ipv4.tcp_syncookies=0 need kernel version 4.4 or newer
        #security.alpha.kubernetes.io/sysctls: "net.ipv4.tcp_syncookies=0,net.ipv4.ip_local_port_range=10000 65535"
        #kernel version 4.15 needed
        #security.alpha.kubernetes.io/unsafe-sysctls: "net.core.somaxconn=65535,net.ipv4.tcp_tw_reuse=1,net.ipv4.tcp_fin_timeout=30,net.ipv4.tcp_keepalive_intvl=4,net.ipv4.tcp_keepalive_probes=3,net.ipv4.tcp_keepalive_time=120,net.ipv4.tcp_max_syn_backlog=65535,net.ipv4.tcp_rfc1337=1,net.ipv4.tcp_slow_start_after_idle=0,net.ipv4.tcp_fack=1,net.ipv4.tcp_fwmark_accept=1,net.ipv4.fwmark_reflect=1"
    spec:
      #affinity:
      #    anti:
      #      type:
      #        default: preferredDuringSchedulingIgnoredDuringExecution
      #      topologyKey:
      #        default: kubernetes.io/hostname
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: rbd-provisioner
        # Currently outdated, hence use inofficial version
        # built from https://github.com/kubernetes-incubator/external-storage
        # (in ceph/rbd subdir)
        # cf. https://github.com/kubernetes-incubator/external-storage/issues/608
        #image: "quay.io/external_storage/rbd-provisioner:latest"
        #image: anatolyrugalev/rbd-provisioner:latest
        image: slpcat/rbd-provisioner
        env:
        - name: PROVISIONER_NAME
          value: ceph.com/rbd
        #- name: POD_NAME
        #  valueFrom:
        #    fieldRef:
        #      fieldPath: metadata.name
        #- name: DEBUG
        #  value: verbose
        volumeMounts:
        - mountPath: /etc/ceph
          name: ceph-conf
      serviceAccount: rbd-provisioner
      volumes:
      - name: ceph-conf
        secret:
          secretName: ceph-conf-combined
      #imagePullSecrets:
      #- name: regsecret
