apiVersion: v1
kind: Service
metadata:
  name: kafka-manager
spec:
  #headless service
  #clusterIP: None
  ports:
  - name: http
    protocol: TCP
    port: 9000
    targetPort: 9000
  type: NodePort
  selector:
    app: kafka-manager
