#仅限于缓存用途，没有持久存储
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        name: redis
        app: redis
    spec:
      containers:
      - name: redis
        image: slpcat/redis-3.2
        resources:
          # keep request = limit to keep this container in guaranteed class
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 2Gi
        ports:
          - name: redis
            containerPort: 6379
        volumeMounts:
        - name: redis-config
          mountPath: "/etc/redis"
      volumes:
        - name: redis-config
          configMap:
            name: redis-etc-configmap
            #Add ConfigMap data to a specific path in the Volume
            items:
            - key: redis.conf
              path: redis.conf
