apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-jenkins-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: local-jenkins
