apiVersion: v1
kind: Service
metadata:
  name: hbase-master
spec:
  clusterIP: None
  selector:
    app: hbase-master
  ports:
    - name: p1
      port: 16000
    - name: p2
      port: 16010
---
apiVersion: v1
kind: Service
metadata:
  name: hbase-master-ui
spec:
  selector:
    app: hbase-master
  ports:
    - name: p2
      port: 16010
  type: NodePort
