apiVersion: v1
kind: Service
metadata:
  name: hbase-regionserver
spec:
  clusterIP: None
  selector:
    app: hbase-regionserver
  ports:
    - name: p1
      port: 16020
    - name: p2
      port: 16030
