---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: ceph
    daemon: rgw
  name: ceph-rgw
  namespace: ceph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ceph
      daemon: rgw
  template:
    metadata:
      name: ceph-rgw
      namespace: ceph
      labels:
        app: ceph
        daemon: rgw
      #annotations:
        #net.ipv4.tcp_syncookies=0 need kernel version 4.4 or newer
        #security.alpha.kubernetes.io/sysctls: "net.ipv4.tcp_syncookies=0,net.ipv4.ip_local_port_range=10000 65535"
        #kernel version 4.15 needed
        #security.alpha.kubernetes.io/unsafe-sysctls: "net.core.somaxconn=65535,net.ipv4.tcp_tw_reuse=1,net.ipv4.tcp_fin_timeout=30,net.ipv4.tcp_keepalive_intvl=4,net.ipv4.tcp_keepalive_probes=3,net.ipv4.tcp_keepalive_time=120,net.ipv4.tcp_max_syn_backlog=65535,net.ipv4.tcp_rfc1337=1,net.ipv4.tcp_slow_start_after_idle=0,net.ipv4.tcp_fack=1,net.ipv4.tcp_fwmark_accept=1,net.ipv4.fwmark_reflect=1"
    spec:
      nodeSelector:
        node-type: storage
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: ["ceph"]
              - key: daemon
                operator: In
                values: ["rgw"]
            topologyKey: kubernetes.io/hostname
      serviceAccount: default
      volumes:
        - name: ceph-conf
          secret:
            secretName: ceph-conf-combined
        - name: ceph-bootstrap-osd-keyring
          secret:
            secretName: ceph-bootstrap-osd-keyring
        - name: ceph-bootstrap-mds-keyring
          secret:
            secretName: ceph-bootstrap-mds-keyring
        - name: ceph-bootstrap-rgw-keyring
          secret:
            secretName: ceph-bootstrap-rgw-keyring
        - name: ceph-bootstrap-rbd-keyring
          secret:
            secretName: ceph-bootstrap-rbd-keyring
      containers:
        - name: ceph-rgw
          #image: ceph/daemon:latest
          image: slpcat/ceph-daemon:ubuntu16.04
          ports:
            - containerPort: 8080
          env:
            - name: CEPH_DAEMON
              value: RGW
            #- name: RGW_CIVETWEB_PORT
            #  value: "8080"
            #- name: RGW_NAME
            #  value: myrgw
            #- name: RGW_ZONEGROUP
            #  value: ""
            #- name: RGW_ZONE
            #  value: ""
            - name: KV_TYPE
              value: k8s
            - name: CLUSTER
              value: ceph
            #- name: DEBUG
            #  value: verbos
          volumeMounts:
            - name: ceph-conf
              mountPath: /etc/ceph
            - name: ceph-bootstrap-osd-keyring
              mountPath: /var/lib/ceph/bootstrap-osd
            - name: ceph-bootstrap-mds-keyring
              mountPath: /var/lib/ceph/bootstrap-mds
            - name: ceph-bootstrap-rgw-keyring
              mountPath: /var/lib/ceph/bootstrap-rgw
            - name: ceph-bootstrap-rbd-keyring
              mountPath: /var/lib/ceph/bootstrap-rbd
          livenessProbe:
              httpGet:
                path: /
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 5
          readinessProbe:
              httpGet:
                path: /
                port: 8080
              timeoutSeconds: 5
          resources:
            requests:
              memory: "500Mi"
              cpu: ".5"
            limits:
              memory: "4Gi"
              cpu: "4"
