---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  labels:
    app: ceph
    daemon: mon
  name: ceph-mon
  namespace: ceph
spec:
  selector:
    matchLabels:
      app: ceph
      daemon: mon
  template:
    metadata:
      name: ceph-mon
      namespace: ceph
      labels:
        app: ceph
        daemon: mon
      annotations:
        #net.ipv4.tcp_syncookies=0 need kernel version 4.4 or newer
        security.alpha.kubernetes.io/sysctls: "net.ipv4.tcp_syncookies=0,net.ipv4.ip_local_port_range=10000 65535"
        #kernel version 4.15 needed
        #security.alpha.kubernetes.io/unsafe-sysctls: "net.core.somaxconn=65535,net.ipv4.tcp_tw_reuse=1,net.ipv4.tcp_fin_timeout=30,net.ipv4.tcp_keepalive_intvl=4,net.ipv4.tcp_keepalive_probes=3,net.ipv4.tcp_keepalive_time=120,net.ipv4.tcp_max_syn_backlog=65535,net.ipv4.tcp_rfc1337=1,net.ipv4.tcp_slow_start_after_idle=0,net.ipv4.tcp_fack=1,net.ipv4.tcp_fwmark_accept=1,net.ipv4.fwmark_reflect=1"
    spec:
      nodeSelector:
        #node-type: storage
        ceph-mon: enabled
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccount: default
      volumes:
        - name: ceph-conf
          secret:
            secretName: ceph-conf-combined
        - name: ceph-bootstrap-osd-keyring
          secret:
            secretName: ceph-bootstrap-osd-keyring
        - name: ceph-bootstrap-mds-keyring
          secret:
            secretName: ceph-bootstrap-mds-keyring
        - name: ceph-bootstrap-rgw-keyring
          secret:
            secretName: ceph-bootstrap-rgw-keyring
        - name: ceph-bootstrap-rbd-keyring
          secret:
            secretName: ceph-bootstrap-rbd-keyring
        - name: ceph-mon-data
          hostPath:
            path: /var/lib/ceph/mon
      containers:
        - name: ceph-mon
          #image: ceph/daemon:latest
          image: slpcat/ceph-daemon:ubuntu16.04
          imagePullPolicy: Always
          lifecycle:
            preStop:
                exec:
                  # remove the mon on Pod stop.
                  command:
                    - "/remove-mon.sh"
          ports:
            - containerPort: 6789
          env:
            - name: K8S_HOST_NETWORK
              value: "1"
            - name: MONMAP
              value: /var/lib/ceph/mon/monmap
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: CEPH_DAEMON
              value: MON
            - name: KV_TYPE
              value: k8s
            #NETWORK_AUTO_DETECT can't work with calico to get CEPH_PUBLIC_NETWORK
            - name: NETWORK_AUTO_DETECT
              value: "0"
            - name: CLUSTER
              value: ceph
            - name: CEPH_PUBLIC_NETWORK
              value: 10.233.0.0/16
            - name: MON_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MON_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            #- name: DEBUG
            #  value: stayalive
          volumeMounts:
            - name: ceph-conf
              mountPath: /etc/ceph
            - name: ceph-mon-data
              mountPath: /var/lib/ceph/mon
            - name: ceph-bootstrap-osd-keyring
              mountPath: /var/lib/ceph/bootstrap-osd
            - name: ceph-bootstrap-mds-keyring
              mountPath: /var/lib/ceph/bootstrap-mds
            - name: ceph-bootstrap-rgw-keyring
              mountPath: /var/lib/ceph/bootstrap-rgw
            - name: ceph-bootstrap-rbd-keyring
              mountPath: /var/lib/ceph/bootstrap-rbd
          livenessProbe:
              tcpSocket:
                port: 6789
              initialDelaySeconds: 60
              timeoutSeconds: 5
          readinessProbe:
              tcpSocket:
                port: 6789
              timeoutSeconds: 5
