apiVersion: v1
kind: Pod
metadata:
  name: mysql-server
  labels:
    name: mysql-server
spec:
  imagePullSecrets:
  - name: mysql-server-registry
  containers:
  - name: mysql-server
    image: slpcat/mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
      limits:
        memory: "4Gi"
        cpu: "2000m"       
    imagePullPolicy: Always
    ports:
    - name: mysql
      containerPort: 3306
    volumeMounts:
      - name: mysql-data
        mountPath: "/var/lib/mysql"
      - name: mysql-conf
        mountPath: "/etc/mysql/conf.d"
  volumes:
    - name: mysql-data
      persistentVolumeClaim:
        claimName: mysql-data-claim
    - name: mysql-conf
      persistentVolumeClaim:
        claimName: mysql-conf-claim
