apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-conf-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100m
  storageClassName: local-mysql-conf
