apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-server
  labels:
    app: mysql-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql-server
        app: mysql-server
    spec:
      containers:
        - name: mysql-server
          image: slpcat/percona-5.5:latest
          ports:
          - containerPort: 80
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "password"
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "4Gi"
          cpu: "2000m"      
      imagePullPolicy: Always
      ports:
      - name: mysql
        containerPort: 3306
      volumeMounts:
        - name: mysql-data
          mountPath: "/var/lib/mysql"
        - name: mysql-conf
          mountPath: "/etc/mysql/conf.d"
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-claim
        - name: mysql-conf
          persistentVolumeClaim:
            claimName: mysql-conf-claim
