apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketmq-console
  labels:
    app: rocketmq-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-console
  template:
    metadata:
      labels:
        name: rocketmq-console
        app: rocketmq-console
    spec:
      containers:
      - name: rocketmq-console
        image: slpcat/rocketmq-console
        ports:
          - name: web
            containerPort: 8080
        env:
          - name: NAMESRV
            value: "rocketmq-svc:9876"
      #volumeMounts:
      #- name: config-volume
      #  mountPath: /opt/rocketmq-console/bin
      #volumes:
      #  - name: config-volume
      #    configMap:
      #      name: runbroker.sh
