kind: Service
apiVersion: v1
metadata:
  labels:
      app: rocketmq
  name: rocketmq-svc
spec:
  ports:
  - port: 9876
    targetPort: 9876
    name: namesrv
  - port: 10911
    targetPort: 10911
    name: broker
  selector:
    app: rocketmq
