---
kind: Service
apiVersion: v1
metadata:
  labels:
      app: rocketmq
  name: rocketmq-svc
spec:
  ports:
  - port: 9876
    targetPort: 9876
    name: namesrv
  - port: 10911
    targetPort: 10911
    name: broker
  clusterIP: None
  selector:
    app: rocketmq
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rocketmq
  labels:
    app: rocketmq
spec:
  serviceName: rocketmq-svc
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq
  template:
    metadata:
      labels:
        name: rocketmq
        app: rocketmq
    spec:
      containers:
      - name: rocketmq
        image: slpcat/rocketmq
        resources:
          # keep request = limit to keep this container in guaranteed class
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 8000m
            memory: 16Gi
        ports:
          - name: namesrv
            containerPort: 9876
          - name: vip
            containerPort: 10909
          - name: broker
            containerPort: 10911
        volumeMounts:
        - name: rocketmq-store
          mountPath: /opt/rocketmq/store
  volumeClaimTemplates:
  - metadata:
      name: rocketmq-store
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
