apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  name: alicloud-disk-efficiency
parameters:
  regionid: cn-beijing
  type: cloud_efficiency
  zoneid: cn-beijing-e
provisioner: alicloud/disk
reclaimPolicy: Retain
