apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alicloud-disk-ssd
parameters:
  regionid: cn-beijing
  type: cloud_ssd
  zoneid: cn-beijing-e
provisioner: alicloud/disk
reclaimPolicy: Retain
