apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: Deployment
    name: php-apache-cpu
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
