apiVersion: v1
kind: Service
metadata:
  annotations:
    #"internet" or "intranet"
    service.beta.kubernetes.io/alicloud-loadbalancer-address-type: intranet
    #Be "classic" or "vpc"
    service.beta.kubernetes.io/alicloud-loadbalancer-SLBNetworkType: vpc
    #service.beta.kubernetes.io/alicloud-loadbalancer-ProtocolPort: https:443,http:80
    service.beta.kubernetes.io/alicloud-loadbalancer-ChargeType: paybytraffic
    #service.beta.kubernetes.io/alicloud-loadbalancer-Region: 
    service.beta.kubernetes.io/alicloud-loadbalancer-Bandwidth: 50
    #service.beta.kubernetes.io/alicloud-loadbalancer-CertID: ""
    #service.beta.kubernetes.io/alicloud-loadbalancer-HealthCheckFlag: on
    #service.beta.kubernetes.io/alicloud-loadbalancer-HealthCheckType:
    #service.beta.kubernetes.io/alicloud-loadbalancer-HealthCheckURI:
    #service.beta.kubernetes.io/alicloud-loadbalancer-HealthCheckConnectPort:
    #service.beta.kubernetes.io/alicloud-loadbalancer-HealthyThreshold:
    #service.beta.kubernetes.io/alicloud-loadbalancer-UnhealthyThreshold:
    #service.beta.kubernetes.io/alicloud-loadbalancer-HealthCheckInterval:
    #service.beta.kubernetes.io/alicloud-loadbalancer-HealthCheckConnectTimeout:
    #service.beta.kubernetes.io/alicloud-loadbalancer-HealthCheckTimeout:
  labels:
    app: example-web
  name: example-web
  namespace: default
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: example-web
  type: LoadBalancer
