apiVersion: v1
kind: Service
metadata:
  name: example-web
spec:
  #headless service
  #clusterIP: None
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
  selector:
    app: example-web
