apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: alicloud-disk-controller
  name: alicloud-disk-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alicloud-disk-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: alicloud-disk-controller
    spec:
      containers:
      - image: registry-vpc.cn-beijing.aliyuncs.com/acs/alicloud-disk-controller:v1.8.4-b753ad0
        imagePullPolicy: IfNotPresent
        name: alicloud-disk-controller
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kubernetes/
          name: cloud-config
        - mountPath: /var/log/alicloud/
          name: logdir
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: alicloud-disk-controller
      serviceAccountName: alicloud-disk-controller
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        operator: Exists
      volumes:
      - hostPath:
          path: /etc/kubernetes/
          type: ""
        name: cloud-config
      - hostPath:
          path: /var/log/alicloud/
          type: ""
        name: logdir
